package storage

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
)

// DBTX is the slice of pgx behavior the storage structs depend on.
// Both *pgxpool.Pool and pgx.Tx satisfy it, so the same storage code
// can run against the pool normally or inside a transaction later.
type DBTX interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// PGDB wraps a *pgxpool.Pool connected to a hosted Postgres instance.
type PGDB struct {
	pool *pgxpool.Pool
}

// NewPGDB connects to Postgres using DATABASE_URL (from the environment
// or a .env file) and creates all application tables.
func NewPGDB(ctx context.Context) (*PGDB, error) {
	// Load .env if one exists next to the binary. A missing file is not
	// an error here — the variable may be exported in the shell instead.
	// (godotenv never overwrites variables already set in the environment.)
	_ = godotenv.Load()

	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		return nil, fmt.Errorf("DATABASE_URL not set")
	}

	// Unlike sql.Open (lazy — errors surface at first use), pgxpool.New
	// parses the connection string and connects eagerly.
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("failed to parse connection string: %w", err)
	}

	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	p := &PGDB{pool: pool}
	if err := p.init(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to initialize database: %w", err)
	}

	return p, nil
}

// init creates all application tables if they don't exist.
//
// Translation notes vs. the SQLite version:
//   - no PRAGMA block — Postgres always enforces foreign keys; WAL is
//     built into its architecture, not a setting
//   - no "safe migration" ALTER TABLE hacks — this is a fresh database,
//     so the columns those hacks added (coffees.finished_at,
//     brews.is_learning) are declared in the CREATE TABLE directly
func (p *PGDB) init(ctx context.Context) error {
	ddl := []string{
		`CREATE TABLE IF NOT EXISTS coffees (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			origin TEXT,
			roaster TEXT,
			variety TEXT,
			roast_level TEXT,
			processing_method TEXT,
			roast_date TEXT,
			is_finished SMALLINT DEFAULT 0,
			created_at TEXT,
			updated_at TEXT,
			finished_at TEXT
		)`,

		`CREATE TABLE IF NOT EXISTS brews (
			id TEXT PRIMARY KEY,
			coffee_id TEXT NOT NULL,
			tasting_notes TEXT,
			tasting_traits TEXT,
			rating INTEGER,
			recipe TEXT,
			dripper TEXT,
			end_time_minutes INTEGER,
			end_time_seconds INTEGER,
			created_at TEXT,
			is_learning SMALLINT DEFAULT 0,
			FOREIGN KEY (coffee_id) REFERENCES coffees(id) ON DELETE CASCADE
		)`,

		`CREATE INDEX IF NOT EXISTS idx_brews_coffee_id ON brews(coffee_id)`,

		`CREATE TABLE IF NOT EXISTS brewers (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			pokeball_type TEXT NOT NULL,
			recipes TEXT,
			created_at TEXT
		)`,

		// GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so the seed data
		// can still insert explicit ids — ALWAYS would reject them.
		`CREATE TABLE IF NOT EXISTS pokemons (
			id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			type TEXT NOT NULL,
			sprite_path TEXT NOT NULL,
			base_stats TEXT NOT NULL,
			description TEXT
		)`,

		`CREATE TABLE IF NOT EXISTS coffee_pokemon (
			id TEXT PRIMARY KEY,
			coffee_id TEXT NOT NULL,
			pokemon_id INTEGER NOT NULL,
			nickname TEXT,
			level INTEGER DEFAULT 1,
			mapping_confidence REAL,
			description TEXT,
			trait_mapping TEXT,
			created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
			FOREIGN KEY (coffee_id) REFERENCES coffees(id),
			FOREIGN KEY (pokemon_id) REFERENCES pokemons(id),
			UNIQUE (pokemon_id)
		)`,
	}

	for _, stmt := range ddl {
		if _, err := p.pool.Exec(ctx, stmt); err != nil {
			return fmt.Errorf("failed to execute DDL: %w\nStatement: %s", err, stmt)
		}
	}

	return nil
}

// Pool exposes the underlying pool for admin/debug tooling. Application
// data access should depend on DBTX instead.
func (p *PGDB) Pool() *pgxpool.Pool {
	return p.pool
}

// Close closes every connection in the pool. Unlike (*sql.DB).Close it
// returns no error.
func (p *PGDB) Close() {
	p.pool.Close()
}
